### ISSUE TITLE
JsPropertyMap.getAny() -> .getAsAny()

### ISSUE THREAD

**Issue by r0bnewt0n** [google/jsinterop-base#14]
Hi,
The release candidate 1 of jsinterop-base has a method JsPropertyMap.getAny().  But 11 months ago this method was renamed .getAsAny().

Since the API changed a while ago, would it be possible to get a RC2 of this essential library with the new API?  Much code is being written around RC1, and it would be best to get RC2 out with the new API sooner rather than later so that less code will need to be changed later on.  What do you think?

Many thanks,
Rob

**Comment by realityforge** [comment]
I believe the team is trying to get a release out of it. Unfortunately, the `jsinterop-base`/`jsinterop-annotations`/`elemental2` suite is not compatible with gwt 2.8.2 atm. Hopefully this will be resolved in the future.

In the meantime, you can use the unofficial release announced in

https://groups.google.com/forum/#!msg/google-web-toolkit/kmhF7kLPSTk/eTZhrq4uCAAJ

for GWT 2.8.2 compatible variant with those changes.

**Comment by r0bnewt0n** [comment]
Yes I have been using your realityforge jsinterop-base and elemental2 releases.  But I want to use other libraries such as Elemento, and they are stuck on RC1 and use the old API in RC1.  Hence my issue.

Thanks for the update though.

**Comment by realityforge** [comment]
I believe @niloc132 has released a (snapshot) version somewhere that has both the new API and the old API in place for just this reason

**Comment by r0bnewt0n** [comment]
That's helpful to know!  I will chase it up with him...

**Comment by jDramaix** [comment]
JsInterop-base:1.0.0 has been released 4days ago and should be compatible with GWT2.8.2.
Elemental2:1.0.0 has been also released but it's not compatible with GWT 2.8.2. You need to use the last snapshot of GWT
