### ISSUE TITLE
Docu outdated, Version 1.0.0 not compiling

### ISSUE THREAD

**Issue by vruegner** [google/jsinterop-base#18]
When following the instructions to set it up with bazel i get the following error:

ERROR: /home/&lt;name&gt;/.cache/bazel/_bazel_&lt;name&gt;/8c6b2a3b7ef920759046b6771c685747/external/com_google_jsinterop_base/third_party/BUILD:25:12: no such package '@org_gwtproject_gwt//user': The repository '@org_gwtproject_gwt' could not be resolved: Repository '@org_gwtproject_gwt' is not defined and referenced by '@com_google_jsinterop_base//third_party:gwt-javaemul-internal-annotations-j2cl'

When i switch from Version '1.0.0' to 'master' it works.

PS: i edited out my name and replaced it with '&lt;name&gt;'

**Comment by gkdn** [comment]
You might have a mix of different repositories. `branch-v1.0.0` checkouts out particular version of J2CL that provides a binding for `org_gwtproject_gwt` while above error suggests it is not defined.

**Comment by vruegner** [comment]
I loaded the master branch of J2CL in my Workspace file and then jsinterop-base v1.0.0. Guess that solves this, thank you :).
